// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOoAs_v2GkVUIqq2ZETJAPVJYZBp9M2_Q',
    appId: '1:446963677986:web:6a7a8141255a43842f837b',
    messagingSenderId: '446963677986',
    projectId: 'besliyorum-satici-paneli',
    authDomain: 'besliyorum-satici-paneli.firebaseapp.com',
    storageBucket: 'besliyorum-satici-paneli.firebasestorage.app',
    measurementId: 'G-JX2W7N48XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIAzWrPishV1KKdwg4DO8vvoooGf9l0q4',
    appId: '1:446963677986:android:5802205094f88ab92f837b',
    messagingSenderId: '446963677986',
    projectId: 'besliyorum-satici-paneli',
    storageBucket: 'besliyorum-satici-paneli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUFsjjK2UxTFmPsxFgmk9abkAB7XShHW8',
    appId: '1:446963677986:ios:ff42a69a0977948f2f837b',
    messagingSenderId: '446963677986',
    projectId: 'besliyorum-satici-paneli',
    storageBucket: 'besliyorum-satici-paneli.firebasestorage.app',
    iosBundleId: 'com.office701.besliyorumsp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUFsjjK2UxTFmPsxFgmk9abkAB7XShHW8',
    appId: '1:446963677986:ios:994adc1b029c162c2f837b',
    messagingSenderId: '446963677986',
    projectId: 'besliyorum-satici-paneli',
    storageBucket: 'besliyorum-satici-paneli.firebasestorage.app',
    iosBundleId: 'com.example.besliyorumSatici',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOoAs_v2GkVUIqq2ZETJAPVJYZBp9M2_Q',
    appId: '1:446963677986:web:9eee78a536b943832f837b',
    messagingSenderId: '446963677986',
    projectId: 'besliyorum-satici-paneli',
    authDomain: 'besliyorum-satici-paneli.firebaseapp.com',
    storageBucket: 'besliyorum-satici-paneli.firebasestorage.app',
    measurementId: 'G-TFWTBR916X',
  );
}
